// TODO: You should probably be using constants! Try to think of common stuff that we want to ensure is spelled right (like the state of a user or status of a ticket)

export const weddingParty = [
    require("../assets/images/group/74FAB5C2-48D6-4FC2-933A-416F0D56115D.jpg"),
    require("../assets/images/group/81B15150-8AA1-4519-A8F3-BB0984F25098.jpg"),
    require("../assets/images/group/20638682_1620342501371716_7518189627316830200_n.jpg"),
    require("../assets/images/group/EBE68238-BDA2-4D5F-8227-9EA020F992E7.jpg"),
    require("../assets/images/group/IMG_0035 3.jpg"),
    require("../assets/images/group/IMG_0095 2.jpg"),
    require("../assets/images/group/IMG_0130.jpg"),
    require("../assets/images/group/IMG_0235.jpg"),
    require("../assets/images/group/IMG_0249 2.jpg"),
    require("../assets/images/group/IMG_0308.jpg"),
    require("../assets/images/group/IMG_0326 2.jpg"),
    require("../assets/images/group/IMG_0372 2.jpg"),
    require("../assets/images/group/IMG_0378 2.jpg"),
    require("../assets/images/group/IMG_0381 2.jpg"),
    require("../assets/images/group/IMG_0383 2.jpg"),
    require("../assets/images/group/IMG_0420.jpg"),
    require("../assets/images/group/IMG_0424.jpg"),
    require("../assets/images/group/IMG_0425.jpg"),
    require("../assets/images/group/IMG_0426.jpg"),
    require("../assets/images/group/IMG_0430.jpg"),
    require("../assets/images/group/IMG_0431.jpg"),
    require("../assets/images/group/IMG_0433.jpg"),
    require("../assets/images/group/IMG_0434.jpg"),
    require("../assets/images/group/IMG_0490.jpg"),
    require("../assets/images/group/IMG_0764.jpg"),
    require("../assets/images/group/IMG_0929.jpg"),
    require("../assets/images/group/IMG_0432.jpg"),
    require("../assets/images/group/IMG_1329.jpg"),
    require("../assets/images/group/IMG_1638.jpg"),
    require("../assets/images/group/IMG_1638.jpg"),
    require("../assets/images/group/IMG_1779.jpg"),
    require("../assets/images/group/IMG_1785.jpg"),
    require("../assets/images/group/IMG_3393.jpg"),
    require("../assets/images/group/IMG_3129 3.jpg"),
    require("../assets/images/group/IMG_3088 2.jpg"),
    require("../assets/images/group/IMG_3340.jpg"),
    require("../assets/images/group/IMG_3350.jpg"),
    require("../assets/images/group/IMG_3517 3.jpg"),
    require("../assets/images/group/IMG_3890 3.jpg"),
    require("../assets/images/group/IMG_3992 3.jpg"),
    require("../assets/images/group/IMG_4252.jpg"),
    require("../assets/images/group/IMG_4407 3.jpg"),
    require("../assets/images/group/IMG_4553.jpg"),
    require("../assets/images/group/IMG_5285.jpg"),
    require("../assets/images/group/IMG_6502 2.jpg"),
    require("../assets/images/group/IMG_6599 2.jpg"),
    require("../assets/images/group/IMG_6627 3.jpg"),
    require("../assets/images/group/IMG_6750 3.jpg"),
    require("../assets/images/group/IMG_6752 2.jpg"),
    require("../assets/images/group/IMG_6784 2.jpg"),
    require("../assets/images/group/IMG_6787 2.jpg"),
    require("../assets/images/group/IMG_6840.jpg"),
    require("../assets/images/group/IMG_6946.jpg"),
    require("../assets/images/group/IMG_7015.jpg"),
    require("../assets/images/group/IMG_7021.jpg"),
    require("../assets/images/group/IMG_7038.jpg"),
    require("../assets/images/group/IMG_7049.jpg"),
    require("../assets/images/group/IMG_7114.jpg"),
    require("../assets/images/group/IMG_7463 2.jpg"),
    require("../assets/images/group/IMG_7464.jpg"),
    require("../assets/images/group/IMG_7530.jpg"),
    require("../assets/images/group/IMG_7534.jpg"),
    require("../assets/images/group/IMG_7696.jpg"),
    require("../assets/images/group/IMG_8185 2.jpg"),
    require("../assets/images/group/IMG_8489.jpg"),
    require("../assets/images/group/sarahascanio-202.jpg"),
]